#include "ast.c"
#include "typ.c"
#include "wheels/fptr.h"
#include "wheels/macros.h"
#include "wheels/mytypes.h"
#include "wheels/tagged_unions.h"
#include <assert.h>
#include <stdio.h>

typedef struct symbol symbol;
typedef struct symbol {
  item_type *type;
  struct {
    bool is_type : 1; // litterally the type
    bool is_function : 1;
  };
  union {
    usize location;
    astNode *funptr;
  };
} symbol;
static_assert(!(sizeof(symbol) % sizeof(usize)));

item_type *item_type_newStub(AllocatorV typesArena) { return aCreate(typesArena, item_type); }
item_type *item_type_allocate_from(AllocatorV allocator, item_type i) {
  var_ res = item_type_newStub(allocator);
  *res = i;
  return res;
}
struct intHandle {
  bool issigned;
  usize bitcount;
};
item_type *get_itype(struct intHandle h) {
  static mHmap(typeof(h), item_type *) imap = NULL;
  if (!imap) {
    imap = mHmap_init(stdAlloc, typeof(h), item_type *);
    // set up signed and unsigned
    // 8, 16, 32, 64
    usize widths[] = {8, 16, 32, 64};
    foreach (usize j, vla(widths))
      mHmap_set(
          imap,
          ((typeof(h)){
              .issigned = false,
              .bitcount = j,
          }),
          item_type_allocate_from(
              stdAlloc,
              TU_OF(
                  (item_type, item_type_uint),
                  ((item_type_uint){
                      .bitwidth = j,
                      .alignment = j
                  })
              )
          )
      );
  }
  item_type **res = mHmap_get(imap, h);
  if (res)
    return *res;
  else {
    mHmap_set(
        imap,
        h,
        item_type_allocate_from(
            stdAlloc,
            h.issigned
                ? TU_OF(
                      (item_type, item_type_sint),
                      ((item_type_sint){
                          .bitwidth = h.bitcount,
                          .alignment = lineup(h.bitcount, 8) * 8,
                      })
                  )
                : TU_OF(
                      (item_type, item_type_uint),
                      ((item_type_uint){
                          .bitwidth = h.bitcount,
                          .alignment = lineup(h.bitcount, 8) * 8,
                      })
                  )
        )
    );
    res = mHmap_get(imap, h);
    assertMessage(res);
    return *res;
  }
}
item_type *make_ptr(AllocatorV allocator, item_type *type) {
  var_ res = item_type_newStub(allocator);
  *res = TU_OF(
      (item_type, item_type_ptr),
      ((item_type_ptr){
          .type = type
      })
  );
  return res;
}
item_type *make_block(AllocatorV allocator, msList(item_type *) typething) {
  var_ res = item_type_newStub(allocator);
  *res = TU_OF(
      (item_type, item_type_block),
      ((item_type_block){
          .types = typething
      })
  );
  return res;
}

item_type *get_ptr_iType(item_type *t) {
  TU_MATCH(
      (item_type, (*t)),
      (item_type_ptr, {
        return $in.type;
      }),
      (default, {
        assertMessage(
            false,
            "tried to get inner pointer to %s",
            snprint(stdAlloc, "{item_type}", &t).ptr
        );
      })
  );
}
usize get_int_bitwidth(item_type *t) {
  TU_MATCH(
      (item_type, (*t)),
      (item_type_uint, {
        return $in.bitwidth;
      }),
      (item_type_sint, {
        return $in.bitwidth;
      }),
      (default, {
        assertMessage(
            false,
            "tried to bitwidth to %s",
            snprint(stdAlloc, "{item_type}", &t).ptr
        );
      })
  );
}
bool isDigit(u8 u) { return !(u > '9' || u < '0'); }
usize fptr_to_number(fptr f) {
  usize res = 0;
  foreach (u8 *c, span(f.ptr, f.len)) {
    if (!isDigit(*c))
      break;
    res *= 10;
    res += *c - '0';
  }
  return res;
}
bool fptr_is_number(fptr f) {
  foreach (u8 *c, span(f.ptr, f.len))
    if (!isDigit(*c))
      return false;
  return true;
}
symbol *symbolResolve(mList(msHmap(symbol)) symstack, fptr sym) {
  foreach (usize i, range(mList_len(symstack), 0)) {
    var_ v = msHmap_get(mList_arr(symstack)[i - 1], sym);
    if (v)
      return v;
  }
  return NULL;
}

symbol interpret(
    AllocatorV allocator,
    mList(u8) stack,
    mList(usize) stack_frames,
    mList(usize) temp_frames, // generated by begins
    astNode *node,
    mList(msHmap(symbol)) symbols
) {
  defer {
    assertMessage(
        !(mList_len(stack) % 8),
        "last instruction misaligned stack : %s",
        snprint(stdAlloc, "{astNode} , {slice(c8)}", node, node->text).ptr
    );
  };
  /*
   * -- stack frame --
   * type
   * item
   * ...
   */
  switch ((enum builtin_OP)(node->op)) {
    case builtin_NONE: {
      assertMessage(node->text.len);
      if (fptr_is_number(node->text)) {
        usize num = fptr_to_number(node->text);
        usize res = mList_len(stack);
        mList_pushArr(stack, *VLAP((u8 *)&num, sizeof(num)));
        return (symbol){
            .location = res,
            .type = get_itype(
                (struct intHandle){
                    .bitcount = sizeof(u64) * 8,
                    .issigned = 0,
                }
            )
        };
      } else if (node->text.ptr[0] == '"') {
        assertMessage(node->text.ptr[node->text.len - 1] == '"');
        usize res = mList_len(stack);
        mList_pushArr(stack, *VLAP((node->text.ptr + 1), node->text.len - 2));
        mList_push(stack, 0);

        while (mList_len(stack) % 8)
          mList_push(stack, 0);

        usize resp = mList_len(stack);
        mList_pushArr(stack, *VLAP((u8 *)&res, sizeof(res)));

        return (symbol){
            .location = resp,
            .type = make_ptr(
                msHmap_allocator(mList_last(symbols)),
                get_itype(
                    (struct intHandle){
                        .bitcount = 8,
                        .issigned = 1,
                    }
                )
            )
        };
      } else {
        symbol *s = symbolResolve(symbols, node->text);
        assertMessage(s, "unknown symbol %s", snprint(stdAlloc, "{slice(c8)}", node->text).ptr);
        return *s;
      }
    } break;
    case builtin_INIT: {
      assertMessage(EQUAL_ANY(msList_len(node->args), 3, 2));

      if (msList_len(node->args) == 2) {
        var_ last = mList_arr(symbols)[mList_len(symbols) - 1];
        assertMessage(!msHmap_get(last, node->args[0]->text), "symbol already exists in this context");
        msHmap_set(last, node->args[0]->text, interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols));
        var_ v = *msHmap_get(last, node->args[0]->text);
        println(
            "created : {item_type} for {slice(c8)}", v.type,
            node->args[0]->text
        );
      } else {
        var_ type_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols);
        assertMessage(
            type_sym.is_type,
            "INIT expected a type for argument 2 , %s",
            snprint(stdAlloc, "{slice(c8)}", node->text).ptr
        );

        // only integer literals rn
        assertMessage(node->args[2]->op == builtin_NONE && fptr_is_number(node->args[2]->text));
        usize val = fptr_to_number(node->args[2]->text);

        usize t_size = type_size(type_sym.type);
        usize loc = mList_len(stack);

        // Pushing the exact bytes of the integer based on the type's size
        mList_pushArr(stack, *VLAP((u8 *)&val, t_size));

        while (mList_len(stack) % 8)
          mList_push(stack, 0);

        var_ last = mList_arr(symbols)[mList_len(symbols) - 1];
        assertMessage(!msHmap_get(last, node->args[0]->text), "symbol already exists in this context");

        msHmap_set(
            last,
            node->args[0]->text,
            ((symbol){
                .type = type_sym.type,
                .location = loc,
            })
        );
      }
      return (symbol){};
    } break;
    case builtin_UINT:
    case builtin_SINT: {
      assertMessage(msList_len(node->args) == 1);
      assertMessage(fptr_is_number(node->args[0]->text));
      return (symbol){
          .is_type = true,
          .type = get_itype(
              (struct intHandle){
                  .bitcount = fptr_to_number(node->args[0]->text),
                  .issigned = node->op == builtin_SINT,
              }
          )
      };
    } break;
    case builtin_PTR: {
      assertMessage(msList_len(node->args) == 1);
      var_ t = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
      assertMessage(t.is_type, "pointer to non-type");
      ;
      return (symbol){
          .is_type = true,
          .type = make_ptr(msHmap_allocator(mList_last(symbols)), t.type),
      };
    } break;
    case builtin_BLOCK: {
      // (input types)
      // output type
      // (ops ...)

      assertMessage(msList_len(node->args) == 3);
      assertMessage(node->args[0]->op == builtin_NONE); // nothing followed by ()

      var_ result_return_type = msList_init(msHmap_allocator(mList_last(symbols)), item_type *);
      var_ rtype = interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols);
      assertMessage(rtype.is_type || !rtype.type, "return type isnt a type or void");

      foreach (var_ t, vla(*msList_vla(node->args[0]->args))) {
        var_ argtype = interpret(
            allocator,
            stack, stack_frames,
            temp_frames,
            t, symbols
        );
        assertMessage(argtype.is_type);
        msList_push(msHmap_allocator(mList_last(symbols)), result_return_type, argtype.type);
      }
      msList_push(msHmap_allocator(mList_last(symbols)), result_return_type, rtype.type);

      return (symbol){
          .type = make_block(msHmap_allocator(mList_last(symbols)), result_return_type),
          .is_function = 1,
          .funptr = node->args[2],
      };
    } break;
    case builtin_ARG: {
      assertMessage(msList_len(node->args) == 1);
      var_ n = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
      assertMessage(n.type->tag == TU_MK_TAG(item_type, item_type_uint));

      var_ idx = *(usize *)(mList_arr(stack) + n.location);
      var_ argCount = *(usize *)(mList_arr(stack) + mList_last(stack_frames));
      assertMessage(idx < argCount, "arg oob");
      // TODO independent function for this
      return ((symbol *)(mList_arr(stack) + mList_last(stack_frames) + sizeof(usize)))[idx];
    } break;
    // these are implemented with gemini
    case builtin_EQUAL:
    case builtin_MORE:
    case builtin_LESS: {
      assertMessage(msList_len(node->args) == 2);
      var_ a_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
      var_ b_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols);

      assertMessage(!a_sym.is_type && !b_sym.is_type, "cannot perform comparisons on types");

      item_type *ta = a_sym.type;
      item_type *tb = b_sym.type;

      bool a_is_ptr = ta->tag == TU_MK_TAG(item_type, item_type_ptr);
      bool b_is_ptr = tb->tag == TU_MK_TAG(item_type, item_type_ptr);

      usize a_bytes = type_size(ta);
      usize b_bytes = type_size(tb);

      u64 a_val = 0;
      memcpy(&a_val, &mList_arr(stack)[a_sym.location], a_bytes);

      u64 b_val = 0;
      memcpy(&b_val, &mList_arr(stack)[b_sym.location], b_bytes);

      bool a_signed = false, b_signed = false;

      if (!a_is_ptr) {
        a_signed = ta->tag == TU_MK_TAG(item_type, item_type_sint);
        if (a_signed && a_bytes < 8) {
          u64 shift = (8 - a_bytes) * 8;
          a_val = (u64)(((i64)(a_val << shift)) >> shift);
        }
      }

      if (!b_is_ptr) {
        b_signed = tb->tag == TU_MK_TAG(item_type, item_type_sint);
        if (b_signed && b_bytes < 8) {
          u64 shift = (8 - b_bytes) * 8;
          b_val = (u64)(((i64)(b_val << shift)) >> shift);
        }
      }

      u64 res_val = 0;

      if (a_is_ptr || b_is_ptr) {
        // Pointers are just unsigned stack indices, do an unsigned comparison
        switch (node->op) {
          case builtin_EQUAL:
            res_val = (a_val == b_val);
            break;
          case builtin_MORE:
            res_val = (a_val > b_val);
            break;
          case builtin_LESS:
            res_val = (a_val < b_val);
            break;
          default:
            break;
        }
      } else {
        bool compare_signed = a_signed || b_signed;

        // clang-format off
        if (compare_signed) {
          i64 sa = (i64)a_val;
          i64 sb = (i64)b_val;
          switch (node->op) {
            case builtin_EQUAL: res_val = (sa == sb); break;
            case builtin_MORE:  res_val = (sa > sb); break;
            case builtin_LESS:  res_val = (sa < sb); break;
            default: break;
          }
        } else {
          switch (node->op) {
            case builtin_EQUAL: res_val = (a_val == b_val); break;
            case builtin_MORE:  res_val = (a_val > b_val); break;
            case builtin_LESS:  res_val = (a_val < b_val); break;
            default: break;
          }
        }
        // clang-format on
      }

      // Return an 8-bit unsigned integer (u8) to represent the boolean result
      item_type *res_type = get_itype((struct intHandle){.bitcount = 8, .issigned = false});
      usize res_bytes = type_size(res_type);

      usize res_loc = mList_len(stack);
      mList_pushArr(stack, *VLAP((u8 *)&res_val, res_bytes));

      while (mList_len(stack) % 8)
        mList_push(stack, 0);

      return (symbol){
          .type = res_type,
          .location = res_loc,
      };
    } break;
    case builtin_ALLOCA: {
      assertMessage(msList_len(node->args) == 2);

      var_ t = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
      assertMessage(t.is_type);

      var_ count_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols);

      usize count = *(usize *)(&mList_arr(stack)[count_sym.location]);

      usize type_bytes = type_size(t.type);
      usize total_bytes = count * type_bytes;

      // TODO something something alignment
      usize buffer_start = mList_len(stack);
      mList_pushArr(stack, *VLAP((u8 *)NULL, lineup(total_bytes, 8)));

      usize ptr_loc = mList_len(stack);
      mList_pushArr(stack, *VLAP((u8 *)&buffer_start, sizeof(buffer_start)));

      return (symbol){
          .type = make_ptr(msHmap_allocator(mList_last(symbols)), t.type),
          .location = ptr_loc,
      };
    } break;
    case builtin_MOVE: {
      assertMessage(msList_len(node->args) == 2);

      var_ src_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
      var_ dest_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols);

      assertMessage(src_sym.type && src_sym.type->tag == TU_MK_TAG(item_type, item_type_ptr), "move source must be a pointer");
      assertMessage(dest_sym.type && dest_sym.type->tag == TU_MK_TAG(item_type, item_type_ptr), "move destination must be a pointer");

      // Dereference both to get their actual virtual addresses (stack indices)
      usize src_ptr = *(usize *)(&mList_arr(stack)[src_sym.location]);
      usize dest_ptr = *(usize *)(&mList_arr(stack)[dest_sym.location]);

      // The size to copy is the size of the underlying type being pointed to
      item_type *inner_type = get_ptr_iType(src_sym.type);
      usize copy_size = type_size(inner_type);

      assertMessage(dest_ptr + copy_size <= mList_len(stack), "move destination out of bounds");
      assertMessage(src_ptr + copy_size <= mList_len(stack), "move source out of bounds");

      memcpy(
          &mList_arr(stack)[dest_ptr],
          &mList_arr(stack)[src_ptr],
          copy_size
      );

      return (symbol){};
    } break;
    case builtin_WHERE: {
      assertMessage(msList_len(node->args) == 1);

      // Evaluate the argument to get the target symbol
      var_ target = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);

      // Ensure we are taking the address of a concrete variable, not a type or a raw function
      assertMessage(!target.is_type, "cannot take address of a type");
      assertMessage(!target.is_function, "taking address of block/function unsupported here");

      // The target's location (stack index) is its virtual memory address
      usize ptr_val = target.location;

      // Push this pointer value onto the stack
      usize ptr_loc = mList_len(stack);
      mList_pushArr(stack, *VLAP((u8 *)&ptr_val, sizeof(ptr_val)));

      // Return a symbol that represents a pointer to the target's type
      return (symbol){
          .type = make_ptr(msHmap_allocator(mList_last(symbols)), target.type),
          .location = ptr_loc,
      };
    } break;
    case builtin_ADD:
    case builtin_SUB:
    case builtin_MUL:
    case builtin_DIV:
    case builtin_SHR:
    case builtin_SHL:
    case builtin_MOD: {
      assertMessage(msList_len(node->args) == 2);
      var_ a_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
      var_ b_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols);

      assertMessage(!a_sym.is_type && !b_sym.is_type, "cannot perform math on types");

      item_type *ta = a_sym.type;
      item_type *tb = b_sym.type;

      bool a_is_ptr = ta->tag == TU_MK_TAG(item_type, item_type_ptr);
      bool b_is_ptr = tb->tag == TU_MK_TAG(item_type, item_type_ptr);

      assertMessage(!(a_is_ptr && b_is_ptr), "pointer to pointer math unimplemented");

      if (a_is_ptr || b_is_ptr) {
        assertMessage(node->op == builtin_ADD || node->op == builtin_SUB, "only ADD and SUB work on pointers");
        assertMessage(!(b_is_ptr && node->op == builtin_SUB), "cannot subtract a pointer from an integer");
      }

      usize a_bytes = type_size(ta);
      usize b_bytes = type_size(tb);

      u64 a_val = 0;
      memcpy(&a_val, &mList_arr(stack)[a_sym.location], a_bytes);

      u64 b_val = 0;
      memcpy(&b_val, &mList_arr(stack)[b_sym.location], b_bytes);

      bool a_signed = false, b_signed = false;
      usize a_bits = 0, b_bits = 0;
      item_type *ptr_inner_type = NULL;

      if (a_is_ptr) {

        ptr_inner_type = get_ptr_iType(ta);
      } else {
        a_signed = ta->tag == TU_MK_TAG(item_type, item_type_sint);
        a_bits = get_int_bitwidth(ta);
        if (a_signed && a_bytes < 8) {
          u64 shift = (8 - a_bytes) * 8;
          a_val = (u64)(((i64)(a_val << shift)) >> shift);
        }
      }
      if (b_is_ptr) {
        ptr_inner_type = get_ptr_iType(tb);
      } else {
        b_signed = tb->tag == TU_MK_TAG(item_type, item_type_sint);
        b_bits = get_int_bitwidth(tb);
        if (b_signed && b_bytes < 8) {
          u64 shift = (8 - b_bytes) * 8;
          b_val = (u64)(((i64)(b_val << shift)) >> shift);
        }
      }

      item_type *res_type = NULL;
      u64 res_val = 0;

      if (a_is_ptr || b_is_ptr) {
        usize stride = type_size(ptr_inner_type);
        if (!stride)
          stride = 1;

        if (node->op == builtin_ADD) {
          if (a_is_ptr)
            res_val = a_val + (b_val * stride);
          else
            res_val = a_val * stride + b_val;
        } else if (node->op == builtin_SUB) {
          res_val = a_val - (b_val * stride);
        }
        res_type = a_is_ptr ? ta : tb;

      } else {
        usize res_bits = a_bits > b_bits ? a_bits : b_bits;
        bool res_signed = a_signed || b_signed;
        res_type = get_itype((struct intHandle){.bitcount = res_bits, .issigned = res_signed});

        // clang-format off
        if (res_signed) {
          i64 sa = (i64)a_val;
          i64 sb = (i64)b_val;
          switch (node->op) {
            case builtin_ADD: res_val = (u64)(sa + sb); break;
            case builtin_SUB: res_val = (u64)(sa - sb); break;
            case builtin_MUL: res_val = (u64)(sa * sb); break;
            case builtin_DIV: assertMessage(sb, "division by zero"); res_val = (u64)(sa / sb); break;
            case builtin_MOD: assertMessage(sb, "modulo by zero"); res_val = (u64)(sa % sb); break;
            case builtin_SHR: res_val = (u64)(sa >> sb); break;
            case builtin_SHL: res_val = (u64)(sa << sb); break;
            default: break;
          }
        } else {
          switch (node->op) {
            case builtin_ADD: res_val = a_val + b_val; break;
            case builtin_SUB: res_val = a_val - b_val; break;
            case builtin_MUL: res_val = a_val * b_val; break;
            case builtin_DIV: assertMessage(b_val, "division by zero"); res_val = a_val / b_val; break;
            case builtin_MOD: assertMessage(b_val, "modulo by zero"); res_val = a_val % b_val; break;
            case builtin_SHR: res_val = a_val >> b_val; break;
            case builtin_SHL: res_val = a_val << b_val; break;
            default: break;
          }
        }
        // clang-format on
      }

      usize res_bytes = type_size(res_type);
      usize res_loc = mList_len(stack);
      mList_pushArr(stack, *VLAP((u8 *)&res_val, res_bytes));
      while (mList_len(stack) % 8)
        mList_push(stack, 0);

      return (symbol){
          .type = res_type,
          .location = res_loc,
      };
    } break;
    case builtin_CALL: {
      assertMessage(msList_len(node->args) == 2);

      astNode *func_node = node->args[0];
      astNode *args_node = node->args[1];

      // 1. Evaluate arguments before pushing the new frame
      usize arg_count = args_node->op == builtin_NONE ? msList_len(args_node->args) : 0;
      symbol *arg_syms = aCreate(stdAlloc, symbol, arg_count ?: 1);
      if (arg_count) {
        usize i = 0;
        foreach (var_ arg_ast, vla(*msList_vla(args_node->args))) {
          arg_syms[i++] = interpret(allocator, stack, stack_frames, temp_frames, arg_ast, symbols);
        }
      }

      // 2. Intercept native C functions (e.g., puts)
      if (func_node->op == builtin_NONE && !symbolResolve(symbols, func_node->text)) {
        if (fptr_eq(func_node->text, fp("putc"))) {

          assertMessage(arg_count == 1, "putc expects 1 argument");

          symbol c_sym = arg_syms[0];

          char c_val = mList_arr(stack)[c_sym.location];

          putchar(c_val);
          // fflush(stdout);

          return (symbol){};
        }
        assertMessage(false, "unknown native function %s", snprint(stdAlloc, "{slice(c8)}", func_node->text).ptr);
      }

      // 3. Resolve user-defined block
      symbol func_sym = interpret(allocator, stack, stack_frames, temp_frames, func_node, symbols);
      assertMessage(func_sym.is_function, "attempted to call a non-function");

      // 4. Setup Stack Frame
      usize frame_start = mList_len(stack);
      mList_push(stack_frames, frame_start);

      // where ARGS draws from
      // TODO independent function for this
      mList_pushArr(stack, *VLAP((u8 *)&arg_count, sizeof(arg_count)));
      for (usize i = 0; i < arg_count; i++)
        mList_pushArr(stack, *VLAP((u8 *)&(arg_syms[i]), sizeof(arg_syms[i])));

      // Create new lexical scope with its own arena
      AllocatorV parent_alloc = msHmap_allocator(mList_last(symbols));
      AllocatorV scope_alloc = arena_new_ext(parent_alloc, 4096);
      mList_push(symbols, msHmap_init(scope_alloc, symbol));

      // 5. Execute block statements
      astNode *body_tuple = (astNode *)func_sym.funptr;
      assertMessage(body_tuple->op == builtin_NONE, "block body must be a tuple");

      var_ stmts_vla = *msList_vla(body_tuple->args);
      usize num_stmts = msList_len(body_tuple->args);

      // 5a. Pre-pass: Map labels to their index
      msHmap(usize) labels = msHmap_init(scope_alloc, usize);
      for (usize i = 0; i < num_stmts; i++) {
        astNode *stmt = stmts_vla[i];
        if (stmt->op == builtin_LABEL) {
          assertMessage(msList_len(stmt->args) == 1, "LABEL expects 1 argument");
          msHmap_set(labels, stmt->args[0]->text, i);
        }
      }

      // 5b. Execution Loop
      symbol ret_sym = {0};
      for (usize i = 0; i < num_stmts; i++) {
        astNode *stmt = stmts_vla[i];

        if (stmt->op == builtin_LABEL) {
          continue;
        } else if (stmt->op == builtin_JMP) {
          assertMessage(msList_len(stmt->args) == 1, "JMP expects 1 argument");
          usize *target = msHmap_get(labels, stmt->args[0]->text);
          assertMessage(target, "JMP to unknown label: %s", snprint(stdAlloc, "{slice(c8)}", stmt->args[0]->text).ptr);
          i = *target;
          continue;
        } else if (stmt->op == builtin_JMP_IF) {
          assertMessage(msList_len(stmt->args) == 2, "JMP_IF expects 2 arguments");
          var_ cond_sym = interpret(scope_alloc, stack, stack_frames, temp_frames, stmt->args[0], symbols);

          usize cond_bytes = type_size(cond_sym.type);
          u64 cond_val = 0;
          memcpy(&cond_val, &mList_arr(stack)[cond_sym.location], cond_bytes);

          if (cond_val) {
            usize *target = msHmap_get(labels, stmt->args[1]->text);
            assertMessage(target, "JMP_IF to unknown label: %s", snprint(stdAlloc, "{slice(c8)}", stmt->args[1]->text).ptr);
            i = *target;
          }
          continue;
        }

        // Pass the arena down so internal operations use it
        ret_sym = interpret(scope_alloc, stack, stack_frames, temp_frames, stmt, symbols);
        if (stmt->op == builtin_RETURN) {
          break;
        }
      }

      // 6. Teardown
      if (ret_sym.type) {
        // Promote the return type to the parent allocator so it survives the arena cleanup
        ret_sym.type = item_type_allocate_from(parent_alloc, *ret_sym.type);
      } else {
        assertMessage(false, "no return doesnt work rn");
      }

      mList_pop(symbols);
      mList_pop(stack_frames);
      arena_cleanup(scope_alloc);

      return ret_sym;
    } break;
    case builtin_ASSIGN: {
      assertMessage(msList_len(node->args) == 2);

      // Resolve the destination symbol and the source value
      var_ dest_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
      var_ src_sym = interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols);

      assertMessage(!dest_sym.is_type && !src_sym.is_type, "cannot assign to/from a type");
      assertMessage(!dest_sym.is_function, "cannot assign to a function block");

      usize dest_bytes = type_size(dest_sym.type);
      usize src_bytes = type_size(src_sym.type);

      // Handle scalar assignments (<= 8 bytes) with potential sign extension and size casting
      if (dest_bytes <= 8 && src_bytes <= 8) {
        u64 val = 0;
        memcpy(&val, &mList_arr(stack)[src_sym.location], src_bytes);

        // Sign extend if source is a signed integer
        bool src_signed = src_sym.type && src_sym.type->tag == TU_MK_TAG(item_type, item_type_sint);
        if (src_signed && src_bytes < 8) {
          u64 shift = (8 - src_bytes) * 8;
          val = (u64)(((i64)(val << shift)) >> shift);
        }

        // Write the possibly truncated or expanded bytes to the destination
        memcpy(&mList_arr(stack)[dest_sym.location], &val, dest_bytes);
      } else {
        // Raw memory copy fallback for larger types (structs, arrays)
        usize copy_size = dest_bytes < src_bytes ? dest_bytes : src_bytes;
        memcpy(
            &mList_arr(stack)[dest_sym.location],
            &mList_arr(stack)[src_sym.location],
            copy_size
        );
      }

      // Return the destination symbol so chained assignments (e.g. a = b = c) work seamlessly
      return dest_sym;
    } break;
    case builtin_RETURN: {
      assertMessage(msList_len(node->args) == 1);
      return interpret(allocator, stack, stack_frames, temp_frames, node->args[0], symbols);
    } break;
    default: {
      assertMessage(false, "unimplemented %s", builtins[node->op]);
    } break;
  }
}

int main(void) {
  u8 c[] =
      {
#embed "int.txt"
      };
  var_ list = astNode_process_file(stdAlloc, fp(c));
  println("{msList : astNode}", list);
  println("{msList : astNode : numbers}", list);
  var_ stack = mList_init(stdAlloc, u8);

  var_ symbols = mList_init(stdAlloc, msHmap(symbol));
  mList_push(symbols, (msHmap_init(stdAlloc, symbol)));

  foreach (var_ node, vla(*msList_vla(list)))
    interpret(
        stdAlloc,
        stack,
        mList_init(stdAlloc, usize),
        mList_init(stdAlloc, usize),
        node,
        symbols
    );
}
#include "wheels/wheels.h"
