#include "ast.c"
#include "typ.c"
#include "wheels/fptr.h"
#include "wheels/macros.h"
#include "wheels/tagged_unions.h"

typedef struct symbol symbol;
typedef struct symbol {
  item_type *type;
  bool is_type; // litterally the type
  usize location;
} symbol;

constexpr item_type module_baseSymbol[1] = {{.tag = TU_MK_TAG(item_type, item_type_module)}};

item_type *item_type_newStub(AllocatorV typesArena) { return aCreate(typesArena, item_type); }
item_type *item_type_allocate_from(AllocatorV allocator, item_type i) {
  var_ res = item_type_newStub(allocator);
  *res = i;
  return res;
}
struct intHandle {
  bool issigned;
  usize bitcount;
};
item_type *get_itype(struct intHandle h) {
  static mHmap(typeof(h), item_type *) imap = NULL;
  if (!imap) {
    imap = mHmap_init(stdAlloc, typeof(h), item_type *);
    // set up signed and unsigned
    // 8, 16, 32, 64
    usize widths[] = {8, 16, 32, 64};
    foreach (usize j, vla(widths))
      mHmap_set(
          imap,
          ((typeof(h)){
              .issigned = false,
              .bitcount = j,
          }),
          item_type_allocate_from(
              stdAlloc,
              TU_OF(
                  (item_type, item_type_uint),
                  ((item_type_uint){
                      .bitwidth = j,
                      .alignment = j
                  })
              )
          )
      );
  }
  item_type **res = mHmap_get(imap, h);
  if (res)
    return *res;
  else {
    mHmap_set(
        imap,
        h,
        item_type_allocate_from(
            stdAlloc,
            h.issigned
                ? TU_OF(
                      (item_type, item_type_sint),
                      ((item_type_sint){
                          .bitwidth = h.bitcount,
                          .alignment = lineup(h.bitcount, 8) * 8,
                      })
                  )
                : TU_OF(
                      (item_type, item_type_uint),
                      ((item_type_uint){
                          .bitwidth = h.bitcount,
                          .alignment = lineup(h.bitcount, 8) * 8,
                      })
                  )
        )
    );
    res = mHmap_get(imap, h);
    assertMessage(res);
    return *res;
  }
}
item_type *make_ptr(AllocatorV allocator, item_type *type) {
  var_ res = item_type_newStub(allocator);
  *res = TU_OF(
      (item_type, item_type_ptr),
      ((item_type_ptr){
          .type = type
      })
  );
  return res;
}

bool isDigit(u8 u) { return !(u > '9' || u < '0'); }
usize fptr_to_number(fptr f) {
  usize res = 0;
  foreach (u8 *c, span(f.ptr, f.len)) {
    if (!isDigit(*c))
      break;
    res *= 10;
    res += *c - '0';
  }
  return res;
}
bool fptr_is_number(fptr f) {
  foreach (u8 *c, span(f.ptr, f.len))
    if (!isDigit(*c))
      return false;
  return true;
}
symbol *symbolResolve(mList(msHmap(symbol)) symstack, fptr sym) {
  foreach (usize i, range(mList_len(symstack), 0)) {
    var_ v = msHmap_get(mList_arr(symstack)[i - 1], sym);
    if (v)
      return v;
  }
  return NULL;
}

symbol interpret(
    AllocatorV allocator,
    mList(u8) stack,
    mList(usize) stack_frames,
    mList(usize) temp_frames, // generated by begins
    // usize false_frame_idx,
    astNode *node,
    mList(msHmap(symbol)) symbols
) {
  /*
   * -- stack frame --
   * type
   * item
   * ...
   */
  switch ((enum builtin_OP)(node->op)) {
    case builtin_NONE: {
      assertMessage(node->text.len);
      if (fptr_is_number(node->text)) {
        usize num = fptr_to_number(node->text);
        usize res = mList_len(stack);
        mList_pushArr(stack, *VLAP((u8 *)&num, sizeof(num)));
        return (symbol){
            .location = res,
            .type = get_itype(
                (struct intHandle){
                    .bitcount = sizeof(u64) * 8,
                    .issigned = 0,
                }
            )
        };
      } else if (node->text.ptr[0] == '"') {
        assertMessage(node->text.ptr[node->text.len - 1] == '"');
        usize res = mList_len(stack);
        mList_pushArr(stack, *VLAP((node->text.ptr + 1), node->text.len - 2));
        mList_push(stack, 0);

        usize resp = mList_len(stack);
        mList_pushArr(stack, *VLAP((u8 *)&res, sizeof(res)));

        return (symbol){
            .location = resp,
            .type = make_ptr(
                stdAlloc, // TODO use actual storage
                get_itype(
                    (struct intHandle){
                        .bitcount = 8,
                        .issigned = 1,
                    }
                )
            )
        };
      } else {
        symbol *s = symbolResolve(symbols, node->text);
        assertMessage(s, "unknown symbol %s", snprint(stdAlloc, "{slice(c8)}", node->text));
        return *s;
      }
    } break;
    case builtin_INIT: {
      assertMessage(msList_len(node->args) == 2);

      var_ last = mList_arr(symbols)[mList_len(symbols) - 1];
      assertMessage(!msHmap_get(last, node->args[0]->text), "symbol already exists in this context");
      msHmap_set(last, node->args[0]->text, interpret(allocator, stack, stack_frames, temp_frames, node->args[1], symbols));
      // var_ v = *msHmap_get(last, node->args[0]->text);
      // println(
      //     "created : {item_type} for {slice(c8)}", v.type,
      //     node->args[0]->text
      // );
      return (symbol){};
    } break;
    case builtin_UINT:
    case builtin_SINT: {
      assertMessage(msList_len(node->args) == 1);
      assertMessage(fptr_is_number(node->args[0]->text));
      return (symbol){
          .is_type = true,
          .type = get_itype(
              (struct intHandle){
                  .bitcount = fptr_to_number(node->args[0]->text),
                  .issigned = node->op == builtin_SINT,
              }
          )
      };
    } break;
    case builtin_BLOCK: {
      // (input types)
      // output type
      // (ops ...)
      assertMessage(false, "block unimplemented");
    } break;
    default: {
      assertMessage(false, "unimplemented %s", builtins[node->op]);
    } break;
  }
}

int main(void) {
  u8 c[] =
      {
#embed "int.txt"
      };
  var_ list = astNode_process_file(stdAlloc, fp(c));
  println("{msList : astNode}", list);
  println("{msList : astNode : numbers}", list);
  var_ stack = mList_init(stdAlloc, u8);

  var_ symbols = mList_init(stdAlloc, msHmap(symbol));
  mList_push(symbols, msHmap_init(stdAlloc, symbol));
  foreach (var_ node, vla(*msList_vla(list)))
    interpret(
        stdAlloc,
        stack,
        mList_init(stdAlloc, usize),
        mList_init(stdAlloc, usize),
        node,
        symbols
    );
}
#include "wheels/wheels.h"
